=== asdf1234Damian/WebTechnologies/Proyecto/QuestionWriter/build/web/resources/XML/questionario.xsd
<?xml version="1.0"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <!--Elements simples-->
  <xs:element name="autor" type="xs:string"/>
  <xs:element name="fecha" type="xs:string"/>
  <xs:element name="contenido" type="xs:string"/>
  <xs:element name="puntaje" type="xs:integer"/>
  <xs:element name="titulo" type="xs:string"/>
  <xs:element name="grupo" type="xs:string"/>
  <xs:element name="feedbackCorrecto" type="xs:string"/>
  <xs:element name="feedbackIncorrecto" type="xs:string"/>

  <!--Elements complejos-->
  <xs:element name="respuesta">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="contenido"/>
        <xs:element ref="puntaje" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:element name="respuestas">
    <xs:complexType>
      <xs:sequence minOccurs="1" maxOccurs="unbounded">
        <xs:element ref="respuesta" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="sequencial">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="contenido"/>
        <xs:element ref="feedbackCorrecto"/>
        <xs:element ref="feedbackIncorrecto"/>
        <xs:element ref="respuestas"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:element name="parcial">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="contenido"/>
        <xs:element ref="feedbackCorrecto"/>
        <xs:element ref="feedbackIncorrecto"/>
        <xs:element ref="respuestas"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="pregunta">
    <xs:complexType>
      <xs:choice>
        <xs:element ref="sequencial"/>
        <xs:element ref="parcial"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>

  <xs:element name="questionario">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="titulo" maxOccurs="1"/>
        <xs:element ref="autor"/>
        <xs:element ref="grupo"/>
        <xs:element ref="pregunta" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="dataBase">
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="questionario"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== asdf1234Damian/WebTechnologies/Proyecto/QuestionWriter/build/web/resources/XML/questionarioDB.xml
<dataBase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="questionario.xsd">
  <questionario>
    <titulo>Questionario 1</titulo>
    <autor>asdf1234damian@gmail.com</autor>
    <grupo>2CM8</grupo>
    <pregunta>
      <sequencial>
        <contenido>Pregunta uno?</contenido>
        <feedbackCorrecto>:)</feedbackCorrecto>
        <feedbackIncorrecto>:(</feedbackIncorrecto>
        <respuestas>
          <respuesta>
            <contenido> Respuesta A</contenido>
          </respuesta>
          <respuesta>
            <contenido> Respuesta B</contenido>
          </respuesta>
        </respuestas>
      </sequencial>
    </pregunta>
    <pregunta>
      <parcial>
        <contenido>Pregunta dos?</contenido>
        <feedbackCorrecto>:)</feedbackCorrecto>
        <feedbackIncorrecto>:(</feedbackIncorrecto>
        <respuestas>
          <respuesta>
            <contenido>Respuesta A</contenido>
            <puntaje> 5 </puntaje>
          </respuesta>
          <respuesta>
            <contenido>Respuesta b</contenido>
            <puntaje> 5 </puntaje>
          </respuesta>
        </respuestas>
      </parcial>
    </pregunta>
  </questionario>

  
<questionario><titulo>Cuestionario 3 </titulo><autor>asdf1234damian@gmail.com</autor><grupo>3CM2</grupo></questionario></dataBase>
