=== asdf1234Damian/WebTechnologies/Proyecto/QuestionWriter/web/resources/XML/pregunta.xsd
<?xml version="1.0"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="id" type="xs:string"/>
  <xs:element name="feedbackCorrecto" type="xs:string"/>
  <xs:element name="feedbackIncorrecto" type="xs:string"/>
  <xs:element name="feedbackInicial" type="xs:string"/>
  <xs:element name="feedbackEvaluate" type="xs:string"/>
  <xs:element name="feedbackTries" type="xs:string"/>
  <xs:element name="correspondencia" type="xs:string"/>
  <xs:element name="contenido" type="xs:string"/>
  <xs:element name="tipo" type="xs:string"/>
  <xs:element name="puntaje" type="xs:string"/>
  <xs:element name="autor" type="xs:string"/>
  <xs:element name="intentos" type="xs:string"/>
  <xs:element name="current" type="xs:string"/>

  <xs:element name="pregunta">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="id"/>
        <xs:element ref="autor"/>
        <xs:element ref="tipo"/>
        <xs:element ref="contenido"/>
        <xs:element ref="opciones"/>
        <xs:element ref="respuestas"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="opciones">
    <xs:complexType>
      <xs:all>
        <xs:element ref="feedbackCorrecto" minOccurs="0"/>
        <xs:element ref="feedbackIncorrecto" minOccurs="0"/>
        <xs:element ref="feedbackInicial" minOccurs="0"/>
        <xs:element ref="feedbackEvaluate" minOccurs="0"/>
        <xs:element ref="feedbackTries" minOccurs="0"/>
        <xs:element ref="intentos" minOccurs="0"/>
      </xs:all>
    </xs:complexType>
  </xs:element>

  <xs:element name="respuesta">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="contenido"/>
        <xs:choice  minOccurs="0">
          <xs:element ref="puntaje"/>
          <xs:element ref="correspondencia"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="respuestas">
    <xs:complexType>
      <xs:sequence minOccurs="1" maxOccurs="unbounded">
        <xs:element ref="respuesta"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:element name="preguntas">
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="pregunta"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="dataBase">
    <xs:complexType>
      <xs:sequence >
        <xs:element ref="current"/>
        <xs:element ref="preguntas"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== asdf1234Damian/WebTechnologies/Proyecto/QuestionWriter/web/resources/XML/preguntaDB.xml
<dataBase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pregunta.xsd">
  <current>3</current>
  <preguntas>
    <pregunta>
      <id>1</id>
      <autor>asdf1234damian@gmail.com</autor>
      <tipo>secuencial</tipo>
      <contenido>Pregunta 1
      </contenido>
      <opciones>
        <feedbackCorrecto>correcto</feedbackCorrecto>
        <feedbackIncorrecto>icorrecto</feedbackIncorrecto>
        <feedbackInicial>inicial</feedbackInicial>
        <feedbackEvaluate>evaluate</feedbackEvaluate>
        <feedbackTries>tries</feedbackTries>
        <intentos>3</intentos>
      </opciones>
      <respuestas>
        <respuesta>
          <contenido>a</contenido>
          <puntaje>5</puntaje>
        </respuesta>
      </respuestas>
    </pregunta>
    <pregunta>
      <id>2</id>
      <autor>asdf1234damian@gmail.com</autor>
      <tipo>parcial</tipo>
      <contenido>pregunta 2
      </contenido>
      <opciones>
        <feedbackCorrecto>correcto</feedbackCorrecto>
        <feedbackIncorrecto>icorrecto</feedbackIncorrecto>
        <feedbackInicial>inicial</feedbackInicial>
        <feedbackEvaluate>evaluate</feedbackEvaluate>
        <feedbackTries>tries</feedbackTries>
        <intentos>3</intentos>
      </opciones>
      <respuestas>
        <respuesta>
          <contenido>a</contenido>
          <puntaje>5</puntaje>
        </respuesta>
      </respuestas>
    </pregunta>

    <pregunta>
      <id>3</id>
      <autor>asdf1234damian@gmail.com</autor>
      <tipo>parcial</tipo>
      <contenido>pregunta 3</contenido>
      <opciones>
        <feedbackCorrecto>correcto</feedbackCorrecto>
        <feedbackIncorrecto>icorrecto</feedbackIncorrecto>
        <feedbackInicial>inicial</feedbackInicial>
        <feedbackEvaluate>evaluate</feedbackEvaluate>
        <feedbackTries>tries</feedbackTries>
        <intentos>3</intentos>
      </opciones>
      <respuestas>
        <respuesta>
          <contenido>a</contenido>
          <puntaje>5</puntaje>
        </respuesta>
      </respuestas>
    </pregunta>

    <pregunta>
      <id>4</id>
      <autor>peredo@gmia.com</autor>
      <tipo>parcial</tipo>
      <contenido>pregunta 4</contenido>
      <opciones>
        <feedbackCorrecto>correcto</feedbackCorrecto>
        <feedbackIncorrecto>icorrecto</feedbackIncorrecto>
        <feedbackInicial>inicial</feedbackInicial>
        <feedbackEvaluate>evaluate</feedbackEvaluate>
        <feedbackTries>tries</feedbackTries>
        <intentos>3</intentos>
      </opciones>
      <respuestas>
        <respuesta>
          <contenido>a</contenido>
          <puntaje>5</puntaje>
        </respuesta>
      </respuestas>
    </pregunta>

  </preguntas>
</dataBase>
