=== asdf1234Damian/WebTechnologies/Proyecto/QuestionWriter/web/resources/XML/questionario.xsd
<?xml version="1.0"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <!--Elements simples-->
  <xs:element name="autor" type="xs:string"/>
  <xs:element name="fecha" type="xs:string"/>
  <xs:element name="contenido" type="xs:string"/>
  <xs:element name="tipo" type="xs:string"/>
  <xs:element name="puntaje" type="xs:integer"/>
  <xs:element name="titulo" type="xs:string"/>
  <xs:element name="grupo" type="xs:string"/>
  <xs:element name="feedbackCorrecto" type="xs:string"/>
  <xs:element name="feedbackIncorrecto" type="xs:string"/>
  <xs:element name="feedbackInicial" type="xs:string"/>
  <xs:element name="feedbackEvaluate" type="xs:string"/>
  <xs:element name="feedbackTries" type="xs:string"/>
  <xs:element name="navigation" type="xs:string"/>
  <xs:element name="weighting" type="xs:string"/>

  <!--Elements complejos-->

  <xs:element name="opciones">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="feedbackCorrecto"/>
        <xs:element ref="feedbackIncorrecto"/>
        <xs:element ref="feedbackInicial"/>
        <xs:element ref="feedbackEvaluate"/>
        <xs:element ref="feedbackTries"/>
        <xs:element ref="navigation"/>
        <xs:element ref="weighting"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:element name="respuesta">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="contenido"/>
        <xs:element ref="puntaje" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:element name="respuestas">
    <xs:complexType>
      <xs:sequence minOccurs="1" maxOccurs="unbounded">
        <xs:element ref="respuesta" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:element name="pregunta">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tipo"/>
        <xs:element ref="contenido"/>
        <xs:element ref="respuestas"/>
        <xs:element ref="opciones"/>
        <!-- <xs:element ref="recursos"/> -->
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="preguntas">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="pregunta" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="questionario">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="titulo" maxOccurs="1"/>
        <xs:element ref="autor"/>
        <xs:element ref="grupo"/>
        <xs:element ref="preguntas"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="dataBase">
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="questionario"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== asdf1234Damian/WebTechnologies/Proyecto/QuestionWriter/web/resources/XML/questionarioDB.xml
<dataBase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="questionario.xsd">
  <questionario>
    <titulo>Questionario 1</titulo>
    <autor>asdf1234damian@gmail.com</autor>
    <grupo>2CM8</grupo>
    <preguntas>
      <pregunta>
        <tipo>sequencial</tipo>
        <contenido>Relaciona las siguientes analogias pls</contenido>
        <respuestas>
          <respuesta>
            <contenido>Circulo O</contenido>
            <correspondencia>Cuadro</correspondencia>
          </respuesta>
          <respuesta>
            <contenido>Perro</contenido>
            <correspondencia>Gato</correspondencia>
          </respuesta>
          <respuesta>
            <contenido>Ave</contenido>
            <correspondencia>Pez</correspondencia>
          </respuesta>
          <respuesta>
            <contenido>Luz</contenido>
            <correspondencia>Oscuridad</correspondencia>
          </respuesta>
        </respuestas>
        <opciones>
          <navigation>Off</navigation>
          <feedbackInicial>Inicial</feedbackInicial>
          <feedbackEvaluate>Evaluate</feedbackEvaluate>
          <feedbackCorrecto>Correct</feedbackCorrecto>
          <feedbackIncorrecto>Incorrect</feedbackIncorrecto>
          <feedbackTries>Tries</feedbackTries>
          <weighting>5</weighting>
        </opciones>
      </pregunta>
      <pregunta>
        <tipo>parcial</tipo>
        <contenido>Cuanto vale &amp;#960;?</contenido>
        <respuestas>
          <respuesta>
            <contenido>3</contenido>
            <puntaje>0</puntaje>
          </respuesta>
          <respuesta>
            <contenido>2</contenido>
            <puntaje>1</puntaje>
          </respuesta>
          <respuesta>
            <contenido>4</contenido>
            <puntaje>2</puntaje>
          </respuesta>
          <respuesta>
            <contenido>3.14159...</contenido>
            <puntaje>5</puntaje>
          </respuesta>
        </respuestas>
        <opciones>
          <navigation>Off</navigation>
        </opciones>
      </pregunta>
      <pregunta>
        <tipo>parcial</tipo>
        <contenido>Don't</contenido>
        <respuestas>
          <respuesta>
            <contenido>Wanna know</contenido>
            <puntaje>1</puntaje>
          </respuesta>
          <respuesta>
            <contenido>Let me down</contenido>
            <puntaje>2</puntaje>
          </respuesta>
          <respuesta>
            <contenido>Cry</contenido>
            <puntaje>5</puntaje>
          </respuesta>
          <respuesta>
            <contenido>Stop me now</contenido>
            <puntaje>7</puntaje>
          </respuesta>
        </respuestas>
        <opciones>
          <navigation>Off</navigation>
        <feedbackInicial>I'm flying around in ecstasy</feedbackInicial></opciones>
      </pregunta>
    </preguntas>
  </questionario>
  <questionario>
    <titulo>Questionario 2</titulo>
    <autor>asdf1234damian@gmail.com</autor>
    <grupo>2CM9</grupo>
    <preguntas />
  </questionario>
</dataBase>
