=== asdf1234Damian/WebTechnologies/Proyecto/QuestionWriter/web/resources/XML/user.xsd
<?xml version="1.0"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<!--Elementos simples-->
<xs:element name="usrName" type="xs:string"/>
<xs:element name="email" type="xs:string"/>
<xs:element name="pass" type="xs:string" />
<xs:element name="uType" type="xs:string"/>
<xs:element name="grupo" type="xs:string"/>
<!--Elementos complejos-->
<!--Usuario-->
<xs:element name="user">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="usrName"/>
        <xs:element ref="email"/>
        <xs:element ref="pass"/>
        <xs:element ref="uType"/>
        <xs:element ref="grupo" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
</xs:element>
<!--Base de datos de Usuario-->
<xs:element name="dataBase">
 <xs:complexType>
   <xs:sequence>
     <xs:sequence minOccurs="1" maxOccurs="unbounded">
       <xs:element ref="user"/>
     </xs:sequence>
   </xs:sequence>
 </xs:complexType>
</xs:element>

</xs:schema>

=== asdf1234Damian/WebTechnologies/Proyecto/QuestionWriter/build/web/resources/XML/userDB.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataBase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="user.xsd">
  <user>
    <usrName>Damian</usrName>
    <email>asdf1234damian@gmail.com</email>
    <pass>asdf1234</pass>
    <uType>Admin</uType>
  </user>

  <user>
    <usrName>Ruben</usrName>
    <email>ruben@gmail.com</email>
    <pass>asdf1234</pass>
    <uType>Admin</uType>
  </user>

  <user>
    <usrName>Ra√∫l</usrName>
    <email>raul@gmail.com</email>
    <pass>asdf1234</pass>
    <uType>Admin</uType>
    <grupo>2CM8</grupo>
  </user>

  <user>
    <usrName>Vilchis</usrName>
    <email>mafervm@gmail.com</email>
    <pass>asdf1234</pass>
    <uType>Professor</uType>
  </user>

</dataBase>

=== asdf1234Damian/WebTechnologies/Proyecto/QuestionWriter/web/resources/XML/userDB.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataBase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="user.xsd">
  <user>
    <usrName>Damian</usrName>
    <email>asdf1234damian@gmail.com</email>
    <pass>asdf1234</pass>
    <uType>Professor</uType>
  </user>
  
  <user>
    <usrName>Ruben</usrName>
    <email>ruben@gmail.com</email>
    <pass>asdf1234</pass>
    <uType>Admin</uType>
  </user>
  
</dataBase>
